### ISSUE TITLE
Incorrect format for Input string...

### ISSUE THREAD

**Issue by beneliezer** [bsips/lootBoss#1]
Hi There was wondering if you could tell me what would be contributing to these errors?

```
---------> Focus has been set on Discord!
Doing work with LOOT message from Discord
Error: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseUInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToUInt64(String value)
   at lootBoss.Modules.Drop.<PostDropsFromSocketMessage>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at lootBoss.Modules.Sockets.<MessageServerAsync>d__7.MoveNext()
Doing work with LOOT message from Discord
Error: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseUInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToUInt64(String value)
   at lootBoss.Modules.Drop.<PostDropsFromSocketMessage>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at lootBoss.Modules.Sockets.<MessageServerAsync>d__7.MoveNext()
---------> Focus no longer set on Discord
```

**Comment by bsips** [comment]
What do you have set for `discordChannel` in your /resources/config.json?

**Comment by beneliezer** [comment]
#lootz

**Comment by beneliezer** [comment]
does it need to be the 'ID'?

**Comment by bsips** [comment]
Yeah it's expecting the channel ID :)

**Comment by beneliezer** [comment]
much appreciated, testing now, will close momentarily if all goes well :)
